CREATE TABLE currency
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency_code VARCHAR(255),
    exchange_rate DOUBLE PRECISION,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

CREATE INDEX idx_currency_code ON currency (currency_code);
